//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjectIccWorldCupSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminDetail
    {
        public string username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public string Email_ID { get; set; }
        public Nullable<long> Contact_No { get; set; }
        public string Last_Project { get; set; }
    }
}
