//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjectIccWorldCupSpace
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminDBIccWorldCupEntities2 : DbContext
    {
        public AdminDBIccWorldCupEntities2()
            : base("name=AdminDBIccWorldCupEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminDetail> AdminDetails { get; set; }
        public virtual DbSet<CountryDetail> CountryDetails { get; set; }
        public virtual DbSet<MATCH_DETAILS> MATCH_DETAILS { get; set; }
        public virtual DbSet<Players_Detail> Players_Detail { get; set; }
    }
}
