//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjectIccWorldCupSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATCH_DETAILS
    {
        public int MatchNo { get; set; }
        public string Venue { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
        public string Matches { get; set; }
        public Nullable<int> country1 { get; set; }
        public Nullable<int> country2 { get; set; }
    
        public virtual CountryDetail CountryDetail { get; set; }
        public virtual CountryDetail CountryDetail1 { get; set; }
    }
}
