//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjectIccWorldCupSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players_Detail
    {
        public int Id { get; set; }
        public string F_name { get; set; }
        public string L_name { get; set; }
        public int Age { get; set; }
        public string City { get; set; }
        public string Skill { get; set; }
        public string Designation { get; set; }
        public int CountryId { get; set; }
    
        public virtual CountryDetail CountryDetail { get; set; }
    }
}
